export interface StockDetails {
  Symbol: string;
  AssetType: string;
  Name: string;
  Description: string;
  CIK: string;
  Exchange: string;
  Currency: string;
  Country: string;
  Sector: string;
  Industry: string;
  Address: string;
  FiscalYearEnd: string;
  LatestQuarter: string;
  MarketCapitalization: string;
  EBITDA: string;
  PERatio: string;
  PEGRatio: string;
  BookValue: string;
  DividendPerShare: string;
  DividendYield: string;
  EPS: string;
  RevenuePerShareTTM: string;
  ProfitMargin: string;
  OperatingMarginTTM: string;
  ReturnOnAssetsTTM: string;
  ReturnOnEquityTTM: string;
  RevenueTTM: string;
  GrossProfitTTM: string;
  DilutedEPSTTM: string;
  QuarterlyEarningsGrowthYOY: string;
  QuarterlyRevenueGrowthYOY: string;
  AnalystTargetPrice: string;
  TrailingPE: string;
  ForwardPE: string;
  PriceToSalesRatioTTM: string;
  PriceToBookRatio: string;
  EVToRevenue: string;
  EVToEBITDA: string;
  Beta: string;
  "52WeekHigh": string;
  "52WeekLow": string;
  "50DayMovingAverage": string;
  "200DayMovingAverage": string;
  SharesOutstanding: string;
  SharesFloat: string;
  SharesShort: string;
  SharesShortPriorMonth: string;
  ShortRatio: string;
  ShortPercentOutstanding: string;
  ShortPercentFloat: string;
  PercentInsiders: string;
  PercentInstitutions: string;
  ForwardAnnualDividendRate: string;
  ForwardAnnualDividendYield: string;
  PayoutRatio: string;
  DividendDate: string;
  ExDividendDate: string;
  LastSplitFactor: string;
  LastSplitDate: string;
}

export const defaultStockDetails = {
  Symbol: "",
  AssetType: "",
  Name: "",
  Description: "",
  CIK: "",
  Exchange: "",
  Currency: "",
  Country: "",
  Sector: "",
  Industry: "",
  Address: "",
  FiscalYearEnd: "",
  LatestQuarter: "",
  MarketCapitalization: "",
  EBITDA: "",
  PERatio: "",
  PEGRatio: "",
  BookValue: "",
  DividendPerShare: "",
  DividendYield: "",
  EPS: "",
  RevenuePerShareTTM: "",
  ProfitMargin: "",
  OperatingMarginTTM: "",
  ReturnOnAssetsTTM: "",
  ReturnOnEquityTTM: "",
  RevenueTTM: "",
  GrossProfitTTM: "",
  DilutedEPSTTM: "",
  QuarterlyEarningsGrowthYOY: "",
  QuarterlyRevenueGrowthYOY: "",
  AnalystTargetPrice: "",
  TrailingPE: "",
  ForwardPE: "",
  PriceToSalesRatioTTM: "",
  PriceToBookRatio: "",
  EVToRevenue: "",
  EVToEBITDA: "",
  Beta: "",
  "52WeekHigh": "",
  "52WeekLow": "",
  "50DayMovingAverage": "",
  "200DayMovingAverage": "",
  SharesOutstanding: "",
  SharesFloat: "",
  SharesShort: "",
  SharesShortPriorMonth: "",
  ShortRatio: "",
  ShortPercentOutstanding: "",
  ShortPercentFloat: "",
  PercentInsiders: "",
  PercentInstitutions: "",
  ForwardAnnualDividendRate: "",
  ForwardAnnualDividendYield: "",
  PayoutRatio: "",
  DividendDate: "",
  ExDividendDate: "",
  LastSplitFactor: "",
  LastSplitDate: "",
};
